### ISSUE TITLE
matlab language icons

### ISSUE THREAD

**Issue by grinsted** [DanBrooker/file-icons#157]
it'd be great with matlab icons for .m files: Here's an svg: http://imgh.us/prog_matlab.svg

**Comment by natalie-** [comment]
I've been looking into this and found that in order to change ".m" to Matlab, it must no longer also belong to Objective-C methods, as the package assigns icons by file name.  I'm not sure if this is an acceptable solution to the project as a whole, but I have it working like this on my machine.

![matlab screenshot](https://cloud.githubusercontent.com/assets/9995618/10652287/57b14c46-7823-11e5-8856-8a72fed0f9ad.jpg)

**Comment by Alhadis** [comment]
Alright, I'm afraid there's no silver bullet, here. Atom doesn't come bundled with [Linguist](https://github.com/github/linguist), so the program has no way of automatically detecting languages (yet? Heh).

However, I *have* been toying with the idea of adding a feature to allow project-level overrides of certain filetypes. This could either take the form of a `package.json` property...
```json
"file-icons": {
	"*.m": ".matlab-icon",
	"*.m": [".matlab-icon", ".medium-yellow"]
}
```
... and/or leveraging the `.gitattributes` file of the repo itself, in the same fashion as [Linguist does](https://github.com/github/linguist#using-gitattributes):
```
*.m linguist-language=Matlab
```

Obviously, this is somewhat of a kludgy approach - it has to be done manually on a case-by-case basis, but it's a start (and would ensure more accurate representation of files when sharing projects between users).

Thoughts?

**Comment by DanBrooker** [comment]
As you said without comprehensive language detection the best we can do is to use the file extension or file name. 

Most projects wouldn't have an existing package.json, and .gitattributes seem fairly unobtrusive.

**Comment by Alhadis** [comment]
Alright, makes sense. =)

**Comment by Alhadis** [comment]
Guys, I've [opened an issue](https://github.com/DanBrooker/file-icons/issues/359) to monitor progress with v2. You can subscribe there for updates.
