### ISSUE TITLE
Allow Per-Icon configuration, or at least a global icon color.

### ISSUE THREAD

**Issue by Goodwine** [DanBrooker/file-icons#163]
Currently you can choose either no-color (white, I think), or the default color.  
It would be awesome if it was possible to override the default color to one that we choose (so it fits better with different ui themes), but I can see that being hard to make a simple UI, so...  
It would then be awesome if there was a way to set our own "global" color, instead of assuming white.

**Comment by DanBrooker** [comment]
"No colour" is just what ever the theme text colour is. I also haven't seen a solution to setting custom variables that affect a package.

However everything is just css, So if you add the following to your user stylesheet, you can set whatever colour you like, for instance red:
```css
.icon:before {
  color: red;
}
```

**Comment by Alhadis** [comment]
Is this a nonissue? Or is there something to work on here? :)

**Comment by Goodwine** [comment]
I would say that this is a feature request for... "Add an option in the UI that lets me set `.icon:before{color:<color>}` so that I don't have to manually mess with my user stylesheet"

**Comment by Alhadis** [comment]
Why? The stylesheet exists to provide customisation.

I'd rather not bloat the package with unnecessary settings, especially when it involves a fair amount of coding work.

**Comment by Alhadis** [comment]
Also, if you're unaware of exactly what would be involved, I'll give you an outline:

- Register package setting for icon colours
- Set listener to wait for the workspace to load
- Check value of colour setting
- Inject a stylesheet into the DOM to alter the colour of each icon
- Have the stylesheet listen for changes to the option and update whenever it's changed

Since stylesheets are loaded in a specific order, there's a high probability the option might clash with existing user customisations, as well other theme/package-related styling. The potential complications aren't worth the trade-off of sparing a user the effort of "messing with their stylesheet".
