### ISSUE TITLE
Golang icon is so ugly

### ISSUE THREAD

**Issue by thuandt** [DanBrooker/file-icons#310]
![Golang icon](http://storage1.static.itmages.com/i/16/0403/h_1459685484_6971372_1df78d0bd0.png)

How we can fix this?

**Comment by Alhadis** [comment]
Just out of interest, what DPI is your screen? Is it a high-density display (retina) or a standard display?

I'm asking because the Go icon's lines are thicker on my screen (irrespective of colour scheme), and it might actually look a lot uglier on low-res devices.

Either way, I'm thinking we should get rid of the outlined icon and opt for something that's either solid-filled, or clearer. Perhaps the [upper-half of the gopher's head](http://i.stack.imgur.com/2mWEC.png)?

**Comment by thuandt** [comment]
I'm using laptop screen with 1366x768 and external monitor with Full HD resolution. It's standard display.

I'm not sure but I think we can use image without transparent in this case.

**Comment by Alhadis** [comment]
This icon has [always been](https://github.com/DanBrooker/file-icons/issues/216) problematic. Even with [Go-specific styling tweaks](https://github.com/DanBrooker/file-icons/blob/374a3846092310e5ee60071e3798655bd69a7762/styles/icons.less#L121) and motif-sensitive enhancements, it still manages to look ugly to some users.

I think the icon's geometry is just too thin and unsuitable for 16×16 display. Using the head would probably be the way to go; it's even used as the favicon on [Go's homepage](https://golang.org/).

**Comment by Alhadis** [comment]
@thuandt How would this look?

<img width="156" src="https://cloud.githubusercontent.com/assets/2346707/14233183/b34d57f8-fa04-11e5-9864-b215118d7165.png" />

**Comment by thuandt** [comment]
@Alhadis seem ok with me :)
