### ISSUE TITLE
cfml-Icon

### ISSUE THREAD

**Issue by vincentvermeer** [DanBrooker/file-icons#318]
It would be great when you could implement an icon for cfm-files.

**Comment by Alhadis** [comment]
What's that?

**Comment by vincentvermeer** [comment]
A programming language? http://www.adobe.com/products/coldfusion-family.html
There exists free implementions like http://lucee.org, too.

**Comment by Alhadis** [comment]
Right, it's an extension used by ColdFusion. Got it.

**Comment by Alhadis** [comment]
Would this be the best icon to represent ColdFusion files?

<img src="http://icons.iconarchive.com/icons/pit-tux/crystal-bw/256/coldfusion-icon.png" />

**Comment by vincentvermeer** [comment]
That's okay.

**Comment by vincentvermeer** [comment]
Or that?
https://commons.wikimedia.org/wiki/File:Adobe_ColdFusion_10_icon.png

**Comment by Alhadis** [comment]
That's why I asked. Searching for `ColdFusion` tossed up two different results - one that looks distinctive (the one I asked about), and another that looks like it might be easily confused with the icons for `.psd` and `.ai` files:

<img width="143" alt="" src="https://cloud.githubusercontent.com/assets/2346707/14560784/3454d8e0-0355-11e6-8a6f-84358727dddf.png" />

I'm really not familiar with ColdFusion, so I've no idea what would be the most recognisable for its users.

**Comment by Alhadis** [comment]
Personally, I'd prefer the older icon, if for no other reason that it's much more distinctive.

**Comment by vincentvermeer** [comment]
I agree

**Comment by Alhadis** [comment]
Klaar.
