### ISSUE TITLE
.conf files to be more generic

### ISSUE THREAD

**Issue by alexrussell** [DanBrooker/file-icons#331]
In [the current Less](https://github.com/DanBrooker/file-icons/blob/master/styles/file-icons.less#L777-778), `.conf` files get an Nginx icon. My suggestion here would be to show the generic code/cog icon for `.conf` files (i.e. `[data-name$=".conf"]` and add it up with [the general config files part](https://github.com/DanBrooker/file-icons/blob/master/styles/file-icons.less#L256)) and then specifically add `nginx.conf` and the extant `.nginxconf` as Nginx specific icons.

The `.conf` extension is used in all sorts of ways for configuration files, so it seems odd for Nginx to steal `*.conf` for itself. In fact, later on in the file, this generic `.conf` rule has to be [overridden by the apache rules](https://github.com/DanBrooker/file-icons/blob/master/styles/file-icons.less#L1184-1186). Of course, that would still be the case, but at least it'd make a little more sense.

Caveat: I don't know Nginx and its configuration files, but a [quick look at the docs](http://nginx.org/en/docs/beginners_guide.html) says that the standard conf file is `nginx.conf` and nothing else. I can't see mention of this `.nginxconf` file that the Less file thinks is an Nginx file.

I'm happy to submit a PR for this if you agree.

**Comment by Alhadis** [comment]
Aye, go for it.

To be honest, I don't know much about Nginx either, which is why I left the extension as-is. I figured whoever added it has more knowledge about the engine than I do, so I left it be.

However, what you're saying checks out - Linguist's [languages list](https://github.com/github/linguist/blob/c3145d3c08f11048d8de5c755f9f3ad86056f01a/lib/linguist/languages.yml#L2346-L2357) even has no sign of `.conf` being used as a general Nginx extension, so I say go ahead. =)

**Comment by alexrussell** [comment]
Ooh that linguist file is good - it'd be great if they could extract that list as a separate library to pull in (npm, RubyGems, etc.) so any project could use it. In the case of this package it'd likely have to be as part of a build process rather than live in Atom but still.

**Comment by Alhadis** [comment]
Heh, [that actually *is* a RubyGem](https://rubygems.org/gems/github-linguist), mate. =)

Because it's a Ruby program, it's unlikely it'll ever be embedded inside Atom (since there'd suddenly be a hard dependency on Ruby to run) but yeah.

I've actually been going through it recently and adding missing icons. I'm up to the letter "F", heh.

**Comment by alexrussell** [comment]
Yeah but it's the whole package - most people only need the list.

**Comment by Alhadis** [comment]
Well, the list can always be used on its own... it's just a YAML file. =)

However, Linguist performs sophisticated Bayesian classification to distinguish between languages which use the same extension... so there're numerous entries in that list sharing the same extension. I guess it would only get you so far on its own...

**Comment by alexrussell** [comment]
Ahh fair enough. All I was thinking is that they could extract that list out to a separate language-independent (other than being able to read YAML) package that they can use but everyone else can. Saves importing the whole package, but you get the updates provided by using packages. But yeah, if the file alone is nowhere near as useful as the package itself then maybe you're right. Obviously, as you say, for our purposes it's handy.

**Comment by Alhadis** [comment]
Aye.

Anyway, I'll hold off making any modifications to the repo until you submit the PR. =)
