### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Stanzilla** [DanBrooker/file-icons#339]
World of Warcraft addons (and probably some more) have TOC files (http://wow.gamepedia.com/TOC_format) and currently Atom shows the "TeX" icon for them. They don't have any official icon but https://commons.wikimedia.org/wiki/File:ToC_icon.svg would probably a good starting point.

**Comment by Alhadis** [comment]
From what I can gather, LaTeX `.toc` files are tables of contents as well, so a more generic-looking icon is probably a good compromise.

However, this data format intrigues me: it seems [widely-used](https://github.com/search?q=extension%3Atoc+NOT+nothack&type=Code) on GitHub, with most files being misclassified as TeX. This clearly warrants submitting a PR to the site's [language savant](https://github.com/github/linguist/), but I know next-to-nothing about World of Warcraft. Are TOC files a subset of a larger DSL for WoW? Or are they just another INI-like data file?

I'm asking because if I have enough info, I'll look into getting a PR to Linguist to fix that misclassification...

**Comment by Stanzilla** [comment]
It only provides meta information to the manager of those addons and lists the files that have to be loaded in order.

**Comment by Alhadis** [comment]
I'll look into it. Thanks!
