### ISSUE TITLE
set milestones

### ISSUE THREAD

**Issue by developer-leon** [DanBrooker/file-icons#361]
Hi,

So Atom prompts me everyday to update this plugin. I see on the commit log that you push on every small change you made. Instead, could you set milestones and update the plugin only when those milestones are reached, so the update prompt is not presented to us daily?

That'll be great! 
Thanks.

**Comment by Alhadis** [comment]
"Daily", eh? Alright, let's break it down...

<img src="https://cloud.githubusercontent.com/assets/2346707/15175125/5033b920-17a8-11e6-8504-789e0af11024.png" width="500" />

The closest interval between recent releases is two days, and that [was to apply a hotfix](https://github.com/DanBrooker/file-icons/issues/352) to revert [something that'd been added earlier](https://github.com/DanBrooker/file-icons/issues/341). As that particular issue was impossible to reproduce on my end, I was uncertain how many other users were being affected by it. The logical move from a development perspective was to revert it, especially since it was triggered by a [decidedly cosmetic](https://github.com/DanBrooker/file-icons/commit/e93cbf5) addition to the package.

Now, concerning your suggestion of using milestones: it's interesting you bring that up, because that's partly the reason the last few releases have been published as patches instead of deferred to a more "substantial" release. [Development on v2 is well underway](https://github.com/DanBrooker/file-icons/issues/359), and keeping the dev branch in sync with contributions to the master branch is a difficult juggling act. Cutting releases is a good way of preventing things "piling up", which leads to a lot of headache due to the amount of cross-checking on my part when integrating contributions to the v2 branch.

Of course, it's quite easy to criticise the veritable bukkake of *"Iconic April"* (the month when this package exploded with new icons), and with the issue of the unreproducible-bug I described earlier, it would certainly seem like an armageddon of package updates has started hammering you and refused to stop. I can forgive that.

What irks me is this:

>  that you push on every small change you made

You sound like you're unfamiliar with [atomic commits](http://elnur.pro/make-atomic-commits/), and how they reflect a best practice of version control.

**Comment by developer-leon** [comment]
Hi, sorry if this irritated you, it was not the intention. I don't doubt you're doing a good job on maintaining a highly popular OSS package, thumbs up for that!

The reason of my comment is actually, an irritation on my side because of seeing an upgrade alert for this package almost every morning. I just wanted to, from an ignorant perspective of what's going on the dev side, suggest to "keep it easy", after all, it's just about icons :)

Now I have a better picture of it, but nonetheless, less update alerts would be greatly thanked!

Have a nice day!

**Comment by Alhadis** [comment]
Actually, it might have something to do with Atom's servers. I was recently experiencing "issues" checking for updates that weren't there when I checked. The week before that I couldn't access the updates panel *at all*. This might be connected: apparently installing an update that never finished, followed by Atom "resetting itself".

If that's the case, then medium-sized packages like this one have a higher likelihood of timing out than smaller ones.

**Comment by unic8s** [comment]
Hi,

just got here from a quick search on "daily updates" of you package.
Seems that it is still a topic. Would be more convinient to pack updates and these small iterations into at least one release per week.

Would really appreciate it - and I don't think that @developer-leon and I are the only persons who like to see a more "effective" update policy for both sides.

Thanks!
