### ISSUE TITLE
Markdown Preview Icons miss-aligned on restart of Atom

### ISSUE THREAD

**Issue by UndefinedOffset** [DanBrooker/file-icons#414]
Using Atom's One Dark theme if you leave a markdown preview window open in two up (at least) and you close and re-open atom the markdown icon is miss-aligned making it appear high on the tab. Left Tab is the editor, and the right tab is the preview.

![mardown-icon-miss-align](https://cloud.githubusercontent.com/assets/1391558/17437668/66504d82-5af5-11e6-979c-9e473e021ac4.jpg)

**Comment by Alhadis** [comment]
Weird. Seems like it's because the `data-name` attribute is being added at startup to all existing tabs, whereas newly-opened Markdown previews don't add the attribute. This is what's being used by the CSS to apply styling - if you run `$("[data-type=MarkdownPreviewView] > .title").removeAttribute("data-path")` in the dev console after startup, you'll notice the offset disappear.

This will be fixed in v2, because v2 doesn't use attribute selectors for styling icons. Since it's a fairly minor issue, I'll close this... although I'll submit a PR to patch this odd little quirk.
