### ISSUE TITLE
Prolog interpreted as Perl

### ISSUE THREAD

**Issue by Olian04** [DanBrooker/file-icons#424]
`.pl` files containing prolog code are being classified as Perl.

**Comment by Alhadis** [comment]
Currently, the package is only able to match icons based on filename.

Once [v2 drops](https://github.com/DanBrooker/file-icons/issues/359), you'll be better able to customise icons on a per-language basis, rather than a per-filename basis. We're just waiting on Atom v1.11 before we can start testing publicly.
