### ISSUE TITLE
JSX Icon Alignment

### ISSUE THREAD

**Issue by IanVS** [DanBrooker/file-icons#451]
First off, I miss the old react icon for .jsx files and I can't tell where that was done/discussed, but the new icon is also not quite horizontally aligned:

![image](https://cloud.githubusercontent.com/assets/4616705/19818895/ece48a90-9d1f-11e6-9b24-12fddd262f52.png)

**Comment by Alhadis** [comment]
Sigh... I was going to wait until v2 to change the icons, but since there's still blockage on its release (waiting on me/my fault), I may as well action this now.

<img src="https://cloud.githubusercontent.com/assets/2346707/19827100/420d8d26-9dea-11e6-9d07-69ba0cba4f66.png" width="180" alt="Figure 1" />

Don't forget, you can always [adjust the size and choice](https://github.com/DanBrooker/file-icons#customisation) of icon with your user stylesheet. =)
